[tool.black]
line-length = 100
target-version = ["py311", "py312", "py313"]

[tool.ruff]
line-length = 100
target-version = "py311"
cache-dir = ".cache/ruff"

[tool.ruff.lint]
extend-select = ["I", "UP", "B", "C4", "SIM", "PL"]
ignore = ["E501"]

exclude = [".venv", "__pycache__"]

[tool.mypy]
python_version = "3.11"
ignore_missing_imports = true
warn_return_any = true
warn_unused_configs = true
strict_optional = false
exclude = [".venv", "__pycache__"]
incremental = true
cache_dir = ".cache/mypy"

[tool.pytest.ini_options]
minversion = "7.0"
addopts = "-q"
testpaths = ["tests"]
cache_dir = ".cache/pytest"
